## 端口配置
server:
  port: 8086

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.56.1:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1413
    driver-class-name: com.mysql.jdbc.Driver

  ## Redis 配置
  redis:
    ## Redis 数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 192.168.56.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    ## 连接超时时间（毫秒）
    timeout: 6000
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ## 连接池中的最大空闲连接
        max-idle: 8
        ## 连接池中的最小空闲连接
        min-idle: 1
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

## Mybatis 配置
## mybatis.typeAliasesPackage=ren.erdong.domain 试试把这行注释掉
mybatis:
  mapperLocations: classpath:mapper/*.xml