## 端口配置
server:
  port: 8081

## MySQL 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.56.1:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1413
    driver-class-name: com.mysql.jdbc.Driver

## Mybatis 配置
mybatis:
  typeAliasesPackage: ren.erdong.entities
  mapperLocations: classpath:mapper/*.xml